name: image_upload_flutter_firebase
description: Image upload demo with Flutter & Firebase storage

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.3.6
  file_picker: ^5.2.11
  firebase_core: ^2.10.0
  firebase_storage: ^11.1.1
  cloud_firestore: ^4.5.2
  firebase_ui_firestore: ^1.3.2
  cached_network_image: ^3.2.3
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
